/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function greet(a: number, b: number, c: number): void;
export function f_n(): number;
export function f_a_n_random(a: number, b: number): void;
export function __wbg_stats_free(a: number): void;
export function __wbg_get_stats_mean(a: number): number;
export function __wbg_set_stats_mean(a: number, b: number): void;
export function __wbg_get_stats_median(a: number): number;
export function __wbg_set_stats_median(a: number, b: number): void;
export function __wbg_get_stats_avg_deviation(a: number): number;
export function __wbg_set_stats_avg_deviation(a: number, b: number): void;
export function __wbg_get_stats_min(a: number): number;
export function __wbg_set_stats_min(a: number, b: number): void;
export function __wbg_get_stats_max(a: number): number;
export function __wbg_set_stats_max(a: number, b: number): void;
export function __wbg_get_stats_n_shadow_clipping_point(a: number): number;
export function __wbg_set_stats_n_shadow_clipping_point(a: number, b: number): void;
export function __wbg_get_stats_n_midtone_balance(a: number): number;
export function __wbg_set_stats_n_midtone_balance(a: number, b: number): void;
export function stats_sorted_data(a: number, b: number): void;
export function stats_a_n_f64_autostretched(a: number, b: number): void;
export function compute_stats_u8(a: number, b: number, c: number, d: number): number;
export function compute_stats_u16(a: number, b: number, c: number, d: number): number;
export function compute_stats_u32(a: number, b: number, c: number, d: number): number;
export function compute_stats_f32(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
